version: "3.9"
services:
  velocity:
    image: velocity
    ports:
      - "25565:25577"
    environment:
      - OP
  lobby:
    image: lobby
    environment:
      - OP
  manhunt:
    image: manhunt
    depends_on:
      - "velocity"
    environment:
      - OP