version: "3.9"
services:
  velocity:
    image: velocity
    restart: always
    ports:
      - "25565:25577"
    environment:
      - OP
    volumes:
      - /etc/mcinfo:/etc/mcinfo
  lobby:
    image: lobby
    restart: always
    environment:
      - OP
    volumes:
      - /etc/mcinfo:/etc/mcinfo
  manhunt:
    image: manhunt
    restart: always
    depends_on:
      - "velocity"
    environment:
      - OP
  web:
    image: web
    restart: always
    ports:
      - "80:8080"