from paper:17.1

ADD init.ps1 /paper/
ADD server.properties /paper/

ADD plugins/ /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/ManHuntPlus/ManHuntPlus%201.4.0.jar /paper/plugins/
ADD https://dev.bukkit.org/projects/chunky-pregenerator/files/3579684/download /paper/plugins/Chunky-1.2.164.jar
ADD https://storage4e4c489d.blob.core.windows.net/plugins/LuckPerms/LuckPerms-Bukkit-5.3.89.jar /paper/plugins
ADD manhuntdrops/ /server/world/datapacks/manhuntdrops/

ENV Xms='8G'
ENV Xmx='8G'