from paper:17.1

ADD server.properties /paper/

ADD plugins/ /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/ManHuntPlus/ManHuntPlus%201.3.0.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/ChunkPregenerator/ChunkPregenerator-V1.16-3.2.1.jar /paper/plugins
ADD manhuntdrops/ /server/world/datapacks/manhuntdrops/

ENV Xms='8G'
ENV Xmx='8G'