from paper:17.1

#ADD server.properties /paper/

#ADD plugins/ /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/datapacks/01-william-wythers-overhauled-overworld-for-1-17-e2380.zip /server/world/datapacks/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/datapacks/CavesAndCliffsPreview.zip /server/world/datapacks/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/datapacks/nullscape-v1-0-2b.zip /server/world/datapacks/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/datapacks/terralith-v1-6-2.zip /server/world/datapacks/