from paper:latest

#ADD server.properties /paper/

ADD plugins/* /paper/plugins/*
ADD https://storage4e4c489d.blob.core.windows.net/plugins/LibsDisguises-10.0.26-Free.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/ProtocolLib/ProtocolLib-4.7.0.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/BlockHunt/BlockHunt-v0.2.1.jar /paper/plugins/