from amazoncorretto:17-alpine

ADD install-pwsh.sh /
RUN chmod +x /install-pwsh.sh && /install-pwsh.sh

RUN mkdir /paper \
    && mkdir /server \
    && echo 'eula=true' > /server/eula.txt
ADD https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/112/downloads/paper-1.18.1-112.jar /paper/paper.jar
ADD https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar /server/cache/mojang_1.18.1.jar
ADD startup.ps1 /paper/startup.ps1
RUN chmod +x /paper/startup.ps1
ADD server.properties /paper/
ADD plugins/ /paper/plugins/

VOLUME ["/server"]
EXPOSE 25565/tcp
EXPOSE 25565/udp

WORKDIR /server
ENV SERVER_NAME='Paper Server'
ENV Xms='2G'
ENV Xmx='2G'
CMD /paper/startup.ps1