from amazoncorretto:16-alpine

ADD install-pwsh.sh /
RUN chmod +x /install-pwsh.sh && /install-pwsh.sh

RUN mkdir /paper \
    && mkdir /server \
    && echo 'eula=true' > /server/eula.txt
ADD https://papermc.io/api/v2/projects/paper/versions/1.17.1/builds/404/downloads/paper-1.17.1-404.jar /paper/paper.jar
ADD https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar /server/cache/mojang_1.17.1.jar
ADD startup.ps1 /paper/startup.ps1
RUN chmod +x /paper/startup.ps1
ADD server.properties /paper/
ADD plugins/ /paper/plugins/
ADD mc.psm1 /usr/local/share/powershell/Modules/mc/

VOLUME ["/server"]
EXPOSE 25565/tcp
EXPOSE 25565/udp

WORKDIR /server
ENV SERVER_NAME='Paper Server'
ENV Xms='2G'
ENV Xmx='2G'
CMD /paper/startup.ps1