FROM paper:18.1

ADD init.ps1 /paper/
ADD paper.yml /paper/
ADD server.properties /paper/
ADD plugins/ /paper/plugins/
ADD datapacks /server/world/

ADD https://storage4e4c489d.blob.core.windows.net/plugins/LuckPerms/LuckPerms-Bukkit-5.3.89.jar /paper/plugins

ENV Xms='2G'
ENV Xmx='2G'
