from paper:latest

ADD server.properties /paper/

ADD plugins/ /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/Minigames/gson-2.8.0.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/Minigames/Minigames-1.16-SNAPSHOT.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/Minigames/Minigames-Regions-1.16-SNAPSHOT.jar /paper/plugins/
ADD https://storage4e4c489d.blob.core.windows.net/plugins/Minigames/paste-gg-api-1.0.0-20201021.031805-6.jar /paper/plugins/